// FG Auto-Pilot orchestration — decide + dispatch one run. All real I/O is
// injected, so this is unit-testable with no engine, no filesystem, no HTTP.
// Targets come from the connections DB, capped per account at the monthly FG
// allowance (~30) so a run dispatches ~30 invites/account, not every match. The
// engine still skips already-following/invited and caps to live invite credits.
import { shouldFire, cycleKey, nextRun } from '../../src/fg-autopilot.js';
import { readFgList } from '../../src/connections/fg-sync.js';
import { fgListTabName } from '../../src/connections/fg-list.js';
import { dispatchFromRows } from '../../src/connections/fg-list-launch.js';

export function makeAutopilotHandler(deps) {
  const {
    startCloud, runStore, loadConfig, saveRuns,
    sendAlert, now, log, inviteUrl, monthlyBudget, tz = 'Europe/London',
    // Reads the pre-generated per-run invite-list tab. Injected for testability;
    // defaults to the real FG Apps Script reader. (already-invited de-dupe now
    // happens at Generate time, and the engine's own already-following guard is
    // the backstop — so the fire no longer needs getFgState here.)
    readList = (tab) => readFgList(tab),
    // Pre-generate: build the run's invite-list tab when nobody has. Injected
    // (the roster service holds the connections DB and the sheet writer);
    // absent → pre-generate is simply skipped and the old alert stands.
    generateList = null,
    leadDays = 3,
  } = deps;

  // A run fires whatever tab exists. Nobody remembering to press Generate meant
  // nothing went out and an email arrived after the fact — so build the tab a few
  // days EARLY and tell the operator it's there to review. Never touches a tab
  // that already exists: a hand-edited list is the operator's, not ours.
  async function pregenerate(nd) {
    const config = loadConfig() || {};
    if (!generateList) return { skipped: true, reason: 'no-generator' };
    if (!config.enabled) return { skipped: true, reason: 'disabled' };
    if (!Array.isArray(config.pairs) || !config.pairs.length) return { skipped: true, reason: 'no-pairs' };
    const next = nextRun(nd, { days: config.days || [1, 15], enabled: true }, tz);
    if (!next) return { skipped: true, reason: 'no-next-run' };
    const daysAway = (next.getTime() - nd.getTime()) / 86400000;
    if (daysAway > leadDays) return { skipped: true, reason: 'too-early' };
    const runKey = cycleKey(next, tz);
    const tab = fgListTabName(runKey);

    // Tab already there (generated by hand, or by an earlier tick) → leave it.
    // A read FAILURE is not "missing": overwriting on a transient sheet error
    // would wipe a reviewed list, so only an empty-but-readable tab generates.
    let existing;
    try { existing = await readList(tab); }
    catch (e) { return { skipped: true, reason: 'read-failed', error: e.message, tab }; }
    if (existing && existing.length >= 2) return { skipped: true, reason: 'already-generated', tab };

    try {
      const out = await generateList(tab, {
        pairs: config.pairs, keywords: config.keywords || [], month: runKey.slice(0, 7),
      });
      const n = (out && out.count) || 0;
      log(`pre-generated ${tab} — ${n} people`);
      try {
        await sendAlert(
          `FG list ready for ${runKey} — ${n} people`,
          `Auto-Pilot built the invite list for ${runKey} (tab "${tab}").\n\n`
          + `${n} people, ${(config.pairs || []).length} accounts. It fires automatically at 06:00 London on ${runKey}.\n\n`
          + `Review or edit the tab any time before then — the run sends whatever the tab says. Delete a row to drop that person.`,
        );
      } catch (_) { /* alerting must never fail the generate */ }
      return { generated: true, tab, count: n, runKey };
    } catch (e) {
      log(`pre-generate failed for ${tab}: ${e.message}`);
      try { await sendAlert(`⚠️ FG Auto-Pilot could not build the list for ${runKey}`, `Tab: ${tab}\nError: ${e.message}\n\nGenerate it by hand from the FG board, or the ${runKey} run will send nothing.`); } catch (_) {}
      return { failed: true, error: e.message, tab, runKey };
    }
  }

  return {
    pregenerate,
    async run({ force = false, nowDate } = {}) {
      const nd = nowDate || new Date(now());
      const config = loadConfig() || {};
      const ranKeys = (runStore.load() || []).map((r) => r.cycleKey).filter(Boolean);

      // Daily tick: build the NEXT run's list if it's close and missing. Runs
      // before the fire gate, and never for today's run (nextRun is strictly in
      // the future), so it can't race the dispatch below.
      let pregen = null;
      if (!force) { try { pregen = await pregenerate(nd); } catch (_) { pregen = null; } }

      let key;
      if (force) {
        // Manual "Run now": bypass the gate, but still need pairs to do anything.
        if (!Array.isArray(config.pairs) || !config.pairs.length) return { skipped: true, reason: 'no-pairs' };
        const manualN = ranKeys.filter((k) => k.startsWith(cycleKey(nd, tz) + '-manual-')).length + 1;
        key = `${cycleKey(nd, tz)}-manual-${manualN}`;
      } else {
        const decision = shouldFire(nd, config, ranKeys, tz);
        if (!decision.fire) return { skipped: true, reason: decision.reason, pregen };
        key = decision.cycleKey;
      }

      const month = cycleKey(nd, tz).slice(0, 7); // YYYY-MM
      // The invite list is now a pre-generated, editable Google Sheet tab (FG board
      // → "Generate list"). The fire READS that tab and works down it — it no longer
      // builds the list itself. The tab is named for the run day, so a list made
      // ahead of time is picked up on the 1st/15th. A "Run now" (force) reads the
      // upcoming run's tab (same one Generate wrote). Missing tab → skip + alert.
      const runCycleKey = force
        ? cycleKey(nextRun(nd, { days: config.days || [1, 15], enabled: true }) || nd, tz)
        : key;
      const tab = fgListTabName(runCycleKey);

      let rows;
      try {
        rows = await readList(tab);
      } catch (e) {
        runStore.add({ cycleKey: key, status: 'failed', error: e.message, dispatchedAt: now(), source: force ? 'manual' : 'auto' });
        saveRuns();
        try { await sendAlert(`⚠️ FG Auto-Pilot could not read the list — ${key}`, `Tab: ${tab}\nError: ${e.message}`); } catch (_) {}
        return { failed: true, error: e.message, cycleKey: key, tab };
      }
      if (!rows || rows.length < 2) {
        // No list generated for this run — the operator hasn't pressed Generate.
        // Alert (not a failure, so it doesn't block a later re-fire once generated).
        try { await sendAlert(`FG Auto-Pilot — no invite list for ${tab}`, `Nothing fired for ${key}.\n\nGenerate the list first: FG board → "Generate list from roles". The scheduled run reads whatever tab exists.`); } catch (_) {}
        return { skipped: true, reason: 'no-list', cycleKey: key, tab };
      }

      const accountEmails = Object.fromEntries((config.pairs || []).map((p) => [p.profileId, p.account]));
      const result = await dispatchFromRows(rows, {
        accountEmails,
        campaign: {
          // Run day, not month — two runs a month otherwise share one name.
          // `key` carries the -manual-N suffix on a forced run, which is exactly
          // what distinguishes it on the board.
          name: `Team Follower Growth · ${key} · auto`,
          owner: config.publishedBy || '',
          config: { inviteUrl, monthlyBudget },
        },
      }, { startCloud });

      if (result.error) {
        // A list with no usable rows (all bad accounts) is benign — don't record a
        // `failed` run (that would block a re-fire once the tab is fixed).
        if (/^No invites to send/.test(result.error)) {
          return { skipped: true, reason: 'no-usable-rows', cycleKey: key, tab, listSkipped: result.skipped || [] };
        }
        runStore.add({ cycleKey: key, status: 'failed', error: result.error, dispatchedAt: now(), source: force ? 'manual' : 'auto', tab });
        saveRuns();
        try { await sendAlert(`⚠️ FG Auto-Pilot run failed — ${key}`, `Cycle ${key}\nTab: ${tab}\nError: ${result.error}`); }
        catch (_) { /* alerting must never mask the original failure */ }
        return { failed: true, error: result.error, cycleKey: key, tab };
      }

      runStore.add({
        cloudId: result.cloudId, cycleKey: key, source: force ? 'manual' : 'auto',
        month, tab, listDriven: true, perAccount: result.perAccount || [],
        dispatchedAt: now(),
      });
      saveRuns();
      return { dispatched: true, cloudId: result.cloudId, cycleKey: key, tab, listSkipped: result.skipped || [], pregen };
    },
  };
}
