import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import { readFileSync } from 'node:fs';
const source = readFileSync(new URL('../public/js/app.js', import.meta.url), 'utf8');
const start = source.indexOf('let _activeCardHome = null;');
const code = source.slice(start, source.indexOf("if (typeof window !== 'undefined') window.placeLiveCard", start));
const classes = () => { const c = new Set(); return { add: (...v) => v.forEach(x => c.add(x)), remove: (...v) => v.forEach(x => c.delete(x)), contains: x => c.has(x) }; };
test('existing campaign retains full live card, dashboard hides it, reopening restores it', () => {
  const card = { style: { display: 'none' }, classList: classes() };
  const home = { id: 'dashboard-view', insertBefore(node) { node.parentElement = this; } };
  card.parentElement = home;
  const slot = { id: 'wiz-live-slot', appendChild(node) { node.parentElement = this; } };
  const sec = { style: { display: '' }, classList: classes() };
  const elements = { 'active-card': card, 'wiz-live-slot': slot, 'nav-status': sec };
  const ctx = vm.createContext({ document: { getElementById: id => elements[id] }, location: { hash: '#/new' }, isOnNewCampaignView: () => false });
  vm.runInContext(code, ctx);
  ctx.placeLiveCard();
  assert.equal(card.parentElement, slot);
  assert.equal(card.style.display, '');
  assert.ok(sec.classList.contains('is-card-live'));
  ctx.location.hash = '#/';
  ctx.placeLiveCard();
  assert.equal(card.style.display, 'none');
  ctx.location.hash = '#/new';
  ctx.placeLiveCard();
  assert.equal(card.parentElement, slot);
  assert.equal(card.style.display, '');
  assert.ok(card.classList.contains('in-wizard'));
});
