#!/usr/bin/env bash
# Build the standalone kubeconfig the development tunnel authenticates with.
#
# `gcloud auth login` expires nightly under the Workspace session policy. When it
# does, the supervisor in electron-dev-vm.sh cannot reconnect the port-forward,
# and the app quietly shows whatever the VM last said — measured 2026-08-28 as a
# campaign card frozen at 01:27 while the engine swept normally all night.
#
# This writes a kubeconfig that carries a Kubernetes ServiceAccount token
# instead. The cluster mints it, so it does not expire with the human session and
# kubectl never consults gcloud. Your normal kubectl and gcloud are untouched:
# only electron-dev-vm.sh reads this file.
#
# Prerequisite (run once, needs a live gcloud session):
#   kubectl apply -f ../ortus-salesnav-scraper-cloud/k8s-dev/30-tunnel-serviceaccount.yaml
#
# Re-run this script only if the ServiceAccount is ever recreated.
set -euo pipefail

NAMESPACE="salesnav-dev"
SA_SECRET="ortus-dev-tunnel-token"
OUT="${ORTUS_DEV_KUBECONFIG:-$HOME/.kube/ortus-dev.yaml}"

CLUSTER="$(kubectl config view --minify -o jsonpath='{.clusters[0].name}')"
SERVER="$(kubectl config view --minify -o jsonpath='{.clusters[0].cluster.server}')"
CA="$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.certificate-authority-data}')"

if [ -z "$SERVER" ] || [ -z "$CA" ]; then
  echo "Could not read the cluster address from your current kubectl context."
  echo "Run: gcloud container clusters get-credentials <cluster> --region <region>"
  exit 1
fi

TOKEN="$(kubectl -n "$NAMESPACE" get secret "$SA_SECRET" -o jsonpath='{.data.token}' | base64 -d)"
if [ -z "$TOKEN" ]; then
  echo "The tunnel ServiceAccount token is missing. Apply the manifest first:"
  echo "  kubectl apply -f ../ortus-salesnav-scraper-cloud/k8s-dev/30-tunnel-serviceaccount.yaml"
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
umask 077
cat > "$OUT" <<EOF
# Generated by scripts/dev-tunnel-kubeconfig.sh — do not edit by hand.
# Carries a non-expiring Kubernetes ServiceAccount token for the dev tunnel.
apiVersion: v1
kind: Config
clusters:
  - name: $CLUSTER
    cluster:
      server: $SERVER
      certificate-authority-data: $CA
users:
  - name: ortus-dev-tunnel
    user:
      token: $TOKEN
contexts:
  - name: ortus-dev-tunnel
    context:
      cluster: $CLUSTER
      user: ortus-dev-tunnel
      namespace: $NAMESPACE
current-context: ortus-dev-tunnel
EOF
chmod 600 "$OUT"

if KUBECONFIG="$OUT" kubectl -n "$NAMESPACE" get deploy salesnav-scraper >/dev/null 2>&1; then
  echo "Development tunnel credential written to $OUT"
  echo "It does not expire. electron-dev-vm.sh picks it up automatically."
else
  echo "Wrote $OUT, but it cannot read the development namespace yet."
  echo "Confirm the RBAC in k8s-dev/30-tunnel-serviceaccount.yaml was applied."
  exit 1
fi
